server:
  port: 8000

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

  #配置 Jpa
  jpa:
    properties:
      hibernate:
        # 指定hibernate方言,jpa默认建表时用的引擎为MyISAM，而MyISAM却是不支持事务的，要想支持需要将表的存储引擎设为InnoDB
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true # 延续session到返回视图层,解决多表关联时的延迟加载

  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 100
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 2000
        #最大空闲
        max-idle: 500
        #最小空闲
        min-idle: 8
    #连接超时时间
    timeout: 5000


#文件存储
file:
  # 文件大小 /M
  max-size: 15

#验证码有效时间/分钟
code:
  expiration: 5